---
- name: A simple Load Balanced AWS server
  hosts: localhost 
  connection: local
  gather_facts: false
  tasks:
    - name: Create security group
      ec2_group:
        name: "demo_security_group"
        description: "demo security group"
        aws_access_key:           
        aws_secret_key: 
        region: "{{ region }}"
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: demo_firewall

    - name: Create an EC2 instance
      ec2:
        aws_access_key:           
        aws_secret_key: 
        key_name: "{{ pem_key }}"
        region: "{{ region }}"
        group_id: "{{ demo_firewall.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        instance_tags:
            env: "{{ env }}"
        count_tag: env
        exact_count: 1
        vpc_subnet_id: subnet-814805af
        assign_public_ip: yes
      register: ec2

#    - name: wait for the servers to appear on the network
#      ec2_instance_info:
#        region: "{{ region }}"
#        filters:
#          "tag:Name": "{{ env }}"
#        aws_access_key:         
#        aws_secret_key: 
#        register: tagged_instances

#    - name: "Debug"
#      debug:
#        var: tagged_instances

    - name: wait for servers to appear on network
      wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=180 state=started
      with_items: '{{ ec2.tagged_instances }}'

    - name: add server ip addresses to hosts group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: '{{ ec2.tagged_instances }}'


- name: spin up the load balancer and add the servers to it
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
    - name: setup a simple load balancer
      ec2_elb_lb:
        name: aws-elb-demo
        state: present
        region: us-east-1
        aws_access_key:           
        aws_secret_key: 
        zones:
          - us-east-1a
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
      register: awselbdemo

    - name: add the webservers to the load balancer
      vars:
        elbvalue: awselbdemo
      local_action: 
        module: ec2_elb
        ec2_elbs: "{{ elbvalue }}"
        instance_id: "{{ item.id }}"        
        aws_access_key:          
        aws_secret_key: 
        state: present
        region: us-east-1
      with_items: "{{ ec2.tagged_instances }}"

- name: installing ,configuring and deploying docker
  roles:
    -  dockers